version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      # - run: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"
      - run:
          name: Deploy to ec2
          command: |
            ssh -oStrictHostKeyChecking=no -i ~/.ssh/circleci $USER@$DNS "bash /tmp/deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy


# jobs:
#   verify-deployment:
#     executor: aws-cli/default
#     steps:
#       - aws-cli/install
#       - aws-cli/setup:
#           aws-access-key-id: AWS_SECRET_ACCESS_KEY
#           aws-region: AWS_DEFAULT_REGION
#           aws-secret-access-key: AWS_DEFAULT_REGION
#       - run:
#           name: Get last task definition
#           command: >  
#             TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
#                 --task-definition ${MY_APP_PREFIX}-service \
#                 --output text \
#                 --query 'taskDefinition.taskDefinitionArn')
#             echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
#             "$BASH_ENV"
#       - aws-ecs/verify-revision-is-deployed:
#           family: '${MY_APP_PREFIX}-service'
#           cluster: '${MY_APP_PREFIX}-cluster'
#           task-definition-arn: '${TASK_DEFINITION_ARN}'

# workflows:
#   build-and-deploy:
#     jobs:
#       - aws-ecr/build-and-push-image: # orb built-in job
#           repo: '${MY_APP_PREFIX}'
#           tag: '${CIRCLE_SHA1}'
#       - aws-ecs/deploy-service-update: # orb built-in job
#           requires:
#             - aws-ecr/build-and-push-image
#           family: '${MY_APP_PREFIX}-service'
#           cluster: '${MY_APP_PREFIX}-cluster'
#           container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
#       - verify-deployment:
#           requires:
#             - aws-ecs/deploy-service-update


version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@x.y.z
  aws-ecs: circleci/aws-ecs@0x.y.z

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"


      # - aws-ecr/push-image:
          # repository: '${MY_APP_PREFIX}'
          # tag: latest
          # region: $AWS_REGION
      # - run: 
          # name : push image


# test
# test