version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v ubuntu@65.0.76.86 "./deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
