version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.9.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running tests
          command: npm test
      - persist_to_workspace:
          root: .          

  deploy:
    docker:
      - image: cimg/node:22.9.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup SSH key
          command: |
            echo "$SSH_PRIVATE_KEY" > /.ssh/id_ed25519
            chmod 600 /.ssh/id_ed25519
            eval $(ssh-agent -s)
            ssh-add /.ssh/id_ed25519
      - run:
          name: AWS EC2 deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@13.232.237.47 << EOF
            echo "Start deploy"
            cd ~/circleci-aws 
            git pull 
            npm install
            npm run build
            pm2 stop build/server 
            pm2 start build/server 
            echo "Deploy end"
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
