version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.9.0
    steps:
      - checkout  # Ensure this is the first step to checkout code
      - run: 
          name: ls
          command: |
            pwd
            ls
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .           
          paths:
            - node_modules  
      - run: 
          name: ls
          command: |
            pwd
            ls

  deploy:
    docker:
      - image: cimg/node:22.9.0
    steps:
      - run: 
          name: ls
          command: |
            pwd
            ls
      - attach_workspace:
          at: .  
      - run: 
          name: ls
          command: |
            pwd
            ls
      - run: 
          name: ssh private key 
          command: echo "$RSA_KEY"
      - run:
          name: Setup SSH key
          command: |
            mkdir -p ~/.ssh
            echo "$RSA_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_rsa
            ssh-add -l
      - run:
          name: AWS EC2 deploy
          command: |
            ssh -o StrictHostKeyChecking=no -v ubuntu@65.0.76.86 
            echo "Start deploy"
            cd ~/circleci-node
            git pull origin main
            npm install
            npm run build
            pm2 stop build/server
            pm2 start build/server
            echo "Deploy end"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
